### ISSUE TITLE
Unexpected Error with R studio script scheduling involving usage of boxR functions

### ISSUE THREAD

**Issue by jf-dmp** [r-box/boxr#125] opened 2019-10-18 18:50 UTC
Dear community member: 

I have an R scripts to schedule run on a regular basis.  It is doing an extraction of files from a box folder into my local R machine for further processing. It works perfectly when I run the whole scripts on my local machine (R-studio). However, it keeping getting the same error on the scheduling part. The place I detected this issue is through the log files that R generated once I put the scripts on scheduling. 

The error are: 

Error in boxGet(file_id, local_file = temp_file, version_id = version_id,  : 
  Error downloading file id 9218868437227407266: Client error: (404) Not Found
Calls: %>% ... freduce -> withVisible -> <Anonymous> -> box_read -> boxGet
Execution halted

Is anyone can provide some explanation on this strange issue? The whole R scripts run perfectly and no error, but when it put on schedule, above error shows and prevent the script from running.

I appreciate a lot!!

Thanks,
Joe

**Comment by nathancday** [comment] 2019-10-20 18:31
Hard to say for sure, can you confirm your scheduled script is able to authenticate?

**Comment by jf-dmp** [comment] 2019-10-21 21:19
Hi Nathan:

Yes, I guess so. I just checked the running history of my R scripts. It started working after failing couple times, which is weird. 

Thanks!!!

Joe

**Comment by nathancday** [comment] 2019-10-22 14:30
I've encountered similar woes with authenticating, multiple attempts before one is successful. Not sure what the root cause is, but it seems to happen more often if I am hitting the Box API quickly in succession. We have tentative plans to add try/check functionality to the authentication functions and hopefully that will be the long term fix for this type of issue.

**Comment by nathancday** [comment] 2019-11-13 18:01
Potential fix in #135

**Closed by nathancday** 2019-11-13 18:01 UTC

**Comment by ijlyttle** [comment] 2019-11-13 20:26
Just to note that in #135, we add a "retry" for auth functions, but not (yet) for the rest of the functions. FWIW, I'd like to bake that into the code in a future release.

**Comment by nathancday** [comment] 2019-11-13 23:49
I like this idea a lot. Mostly everything is a http::POST() call underneath so RETRY() feels like it would be easy to swap in.
