### ISSUE TITLE
request to add option to print URL from box_auth

### ISSUE THREAD

**Issue by bdesmarais** [r-box/boxr#70] opened 2018-05-16 10:18 UTC
This package works perfectly from laptops and desktops, but I can't use box_auth() on my HPC cluster since it doesn't have a browser. It would be great to add an option to box_auth() to print the URL at which to authenticate. This way, I could print the URL from the terminal logged into the cluster, and use the URL to authenticate via a browser on another machine.

**Comment by ijlyttle** [comment] 2018-06-17 15:32
I will have to look into this. 

I'm sure you have seen this workaround, which I fear may be the best we can do for now: https://github.com/brendan-r/boxr/issues/23#issuecomment-258700456

**Comment by ijlyttle** [comment] 2019-10-25 18:43
Closing as duplicate of #23 - help is on the way soon with #105

**Closed by ijlyttle** 2019-10-25 18:43 UTC
