### ISSUE TITLE
box_search() function sometimes cannot find the file

### ISSUE THREAD

**Issue by zeyunlu** [r-box/boxr#65] opened 2017-12-06 20:05 UTC
I have used boxr a lot and I find that the search engine is not stable sometimes.
When the file name, and the ancestor id are provided, it just cannot find the file. 

I write a function that uses box_search to grab the r package that is updated everyday on the box and download it, and use system() to install the package on my local machine. 

Any thoughts on this? or how should I write the function to make it more stable?

**Comment by brendan-r** [comment] 2017-12-09 00:50
Hm. 

> Any thoughts on this? or how should I write the function to make it more stable?

You could see if the problem is with the API or if there's something in the R code that is causing the file to be removed from results somehow. I'd be surprised by the latter, but you never know!

**Comment by brendan-r** [comment] 2019-03-28 22:28
It's been a while, without follow up or further reports, so closing this issue to clear things up. Do respond if this continues to be a problem

**Closed by brendan-r** 2019-03-28 22:28 UTC
